<?php
/**
 * SpamDetectionAdvancedRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SpamDetectionAdvancedRequestTest Class Doc Comment
 *
 * @category    Class
 * @description AI advanced spam detection request
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SpamDetectionAdvancedRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SpamDetectionAdvancedRequest"
     */
    public function testSpamDetectionAdvancedRequest()
    {
    }

    /**
     * Test attribute "input_string"
     */
    public function testPropertyInputString()
    {
    }

    /**
     * Test attribute "model"
     */
    public function testPropertyModel()
    {
    }

    /**
     * Test attribute "allow_unsolicited_sales"
     */
    public function testPropertyAllowUnsolicitedSales()
    {
    }

    /**
     * Test attribute "allow_promotional_content"
     */
    public function testPropertyAllowPromotionalContent()
    {
    }

    /**
     * Test attribute "allow_phishing"
     */
    public function testPropertyAllowPhishing()
    {
    }
}
