<?php
/**
 * SpamDetectionAdvancedResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SpamDetectionAdvancedResponseTest Class Doc Comment
 *
 * @category    Class
 * @description Result of detecting spam using AI
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SpamDetectionAdvancedResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SpamDetectionAdvancedResponse"
     */
    public function testSpamDetectionAdvancedResponse()
    {
    }

    /**
     * Test attribute "clean_result"
     */
    public function testPropertyCleanResult()
    {
    }

    /**
     * Test attribute "contains_spam"
     */
    public function testPropertyContainsSpam()
    {
    }

    /**
     * Test attribute "contains_unsolicited_sales"
     */
    public function testPropertyContainsUnsolicitedSales()
    {
    }

    /**
     * Test attribute "contains_promotional_content"
     */
    public function testPropertyContainsPromotionalContent()
    {
    }

    /**
     * Test attribute "contains_phishing_attempt"
     */
    public function testPropertyContainsPhishingAttempt()
    {
    }
}
